domain: derlin.github.io
url: https://derlin.github.io
baseurl: /docker-compose-viz-mermaid/
repository: derlin/docker-compose-viz

title: "Docker Compose Viz (Mermaid)"
remote_theme: pmarsceill/just-the-docs

color_scheme: light
search_enabled: true

# Footer
footer_content: "Made with ‚ù§ by <a href=\"https://derlin.ch\">derlin</a>"
last_edit_timestamp: true

# Aux links for the upper right navigation
aux_links:
  "View on GitHub":
    - "//github.com/derlin/docker-compose-viz-mermaid"
aux_links_new_tab: true


# Back to top link
back_to_top: true
back_to_top_text: "Back to top"